apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-generator
  labels:
    app: quote-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-generator
  template:
    metadata:
      labels:
        app: quote-generator
    spec:
      containers:
        - name: quote-generator
          image: quote:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"